'use client';

import { Brain } from 'lucide-react';
import { useAuth } from '@/hooks/use-auth';

export default function AdminEnginePage() {
  useAuth(true);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold uppercase tracking-tighter">AI Engine Flux</h1>
        <p className="text-xs text-gray-500 uppercase tracking-widest mt-1">Voting Classifier Calibration</p>
      </div>

      <div className="bg-gray-900/40 border border-gray-800 rounded-2xl p-12">
        <div className="flex flex-col items-center justify-center text-center">
          <div className="w-16 h-16 rounded-full bg-gray-800/60 flex items-center justify-center mb-6">
            <Brain className="w-8 h-8 text-gray-600" />
          </div>
          <h2 className="text-lg font-bold text-gray-300 mb-3 uppercase tracking-tighter">
            AI Voting Classifier Disabled
          </h2>
          <p className="text-sm text-gray-500 max-w-md mb-6">
            The <code className="text-gray-400 bg-gray-800/60 px-1.5 py-0.5 rounded text-xs">neural_models</code> package
            (LSTM, Transformer, XGBoost, Voting, TrainingPipeline) was removed from the codebase.
            It was 1,400+ lines of dead code — <code className="text-gray-400 bg-gray-800/60 px-1.5 py-0.5 rounded text-xs">voting_model.predict()</code> was
            never called, model weights were never trained, and PyTorch was not in <code className="text-gray-400 bg-gray-800/60 px-1.5 py-0.5 rounded text-xs">requirements.txt</code>.
          </p>
          <p className="text-sm text-gray-500 max-w-md">
            Signals are generated by the <span className="text-gray-300 font-bold">ACE Engine</span> (regime-adaptive
            trend continuation + Bollinger reversal) with <span className="text-gray-300 font-bold">Sniper Engine</span> (price-action
            patterns) as fallback. The 12-indicator library (RSI, MACD, BB, EMA, ADX, ATR, Stoch, CCI, OBV, Ichimoku) feeds
            both engines.
          </p>
          <p className="text-xs text-gray-600 mt-6 max-w-md">
            To re-enable AI voting, build a real ML layer from scratch: train models on curated historical data, validate
            out-of-sample accuracy (&ge;60% to be profitable at 70% payout), then re-add <code className="text-gray-500 bg-gray-800/40 px-1.5 py-0.5 rounded text-xs">scikit-learn</code>, <code className="text-gray-500 bg-gray-800/40 px-1.5 py-0.5 rounded text-xs">xgboost</code>, <code className="text-gray-500 bg-gray-800/40 px-1.5 py-0.5 rounded text-xs">torch</code> to <code className="text-gray-500 bg-gray-800/40 px-1.5 py-0.5 rounded text-xs">requirements.txt</code>.
          </p>
        </div>
      </div>
    </div>
  );
}
